### ISSUE TITLE
Cache parts of build on CI

### ISSUE THREAD

**Issue by mscroggs** [bempp/bempp-rs#124]
We should cache the slower parts to build (ie rlst) on the CI runs

**Comment by skailasa** [comment]
It might be sufficient to just run a single (or two incl release mode) test stages, with all features enabled?

**Comment by mscroggs** [comment]
Only running with all features is a good idea, and should make the caching of dependencies work better.

I'm keen to keep both the openmpi and mpich test runs though - early on we had lots of errors that only occurred for one of these and issues like this will be a pain to fix later if we don't keep an eye on them.
