### ISSUE TITLE
SVD-based tests failing intermittently

### ISSUE THREAD

**Issue by mscroggs** [bempp/bempp-rs#148]
The test `fmm::test::test_uniform` is failing on some CI runs (eg https://github.com/bempp/bempp-rs/actions/runs/7476955456/job/20349377073), but passes locally.

We've set the tolerance in this test to be higher to allow it to pass for now: https://github.com/bempp/bempp-rs/blob/9d0e89206f5fd27b17f7b625557d55b8c7c213ba/fmm/src/fmm.rs#L943

**Comment by mscroggs** [comment]
On the same commit [9d0e892](https://github.com/bempp/bempp-rs/pull/141/commits/9d0e89206f5fd27b17f7b625557d55b8c7c213ba), [this CI run failed](https://github.com/bempp/bempp-rs/actions/runs/7477745967/job/20351135929?pr=141) and [this CI run passed](https://github.com/bempp/bempp-rs/actions/runs/7477746379/job/20351137671?pr=141)

**Comment by skailasa** [comment]
This has been found to be due to #151
