### ISSUE TITLE
Document the requirement that the number of processes must be a power of 2

### ISSUE THREAD

**Issue by mscroggs** [bempp/bempp-rs#66]
If I run

```bash
cargo mpirun --example test_adaptive --release -n 3 --features "mpi"
```

I get

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `3`', /home/mscroggs/development/rusty-solvers/hyksort/src/lib.rs:179:9
```

The example runs fine with 2 or 4 processes.

**Comment by skailasa** [comment]
> If I run
> 
> ```shell
> cargo mpirun --example test_adaptive --release -n 3 --features "mpi"
> ```
> 
> I get
> 
> ```
> thread 'main' panicked at 'assertion failed: `(left == right)`
>   left: `2`,
>  right: `3`', /home/mscroggs/development/rusty-solvers/hyksort/src/lib.rs:179:9
> ```
> 
> The example runs fine with 2 or 4 processes.

Hyksort's communication pattern needs the number of processes to be a power of 2.

**Comment by mscroggs** [comment]
Ah so this is a feature, not a bug?

**Comment by skailasa** [comment]
Yes, the communication pattern to work the any number of processes is signifincantly trickier to implement, but does exist. Something to look into in the future, perhaps it should be noted as an issue?
